# Generated by Django 5.0.7 on 2025-09-10 11:23

import datetime
import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Fournisseur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nif', models.CharField(help_text="Numéro d'Identification Fiscale (8 chiffres)", max_length=8, unique=True, validators=[django.core.validators.RegexValidator(message='Le NIF doit contenir exactement 8 chiffres', regex='^\\d{8}$')], verbose_name='NIF')),
                ('raison_sociale', models.CharField(max_length=255, verbose_name='Raison sociale')),
                ('telephone', models.CharField(blank=True, max_length=20, verbose_name='Téléphone')),
                ('adresse', models.TextField(blank=True, verbose_name='Adresse')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('actif', models.BooleanField(default=True, verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
            ],
            options={
                'verbose_name': 'Fournisseur',
                'verbose_name_plural': 'Fournisseurs',
                'ordering': ['raison_sociale'],
            },
        ),
        migrations.CreateModel(
            name='MaterielLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_materiel', models.CharField(choices=[('NIVELEUSE', 'Niveleuse'), ('BULLDOZER', 'Bulldozer'), ('EXCAVATRICE', 'Excavatrice'), ('COMPACTEUR', 'Compacteur'), ('CAMION', 'Camion'), ('VEHICULE_LEGER', 'Véhicule léger'), ('GROUPE_ELECTROGENE', 'Groupe électrogène'), ('AUTRE', 'Autre équipement')], max_length=30, verbose_name='Type de matériel')),
                ('prix_unitaire_mru', models.DecimalField(decimal_places=3, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))], verbose_name='Prix Unitaire TTC')),
                ('observations', models.TextField(blank=True, verbose_name='Observations')),
                ('actif', models.BooleanField(default=True, verbose_name='Disponible à la location')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
            ],
            options={
                'verbose_name': 'Matériel de Location',
                'verbose_name_plural': 'Matériels de Location',
                'ordering': ['type_materiel'],
            },
        ),
        migrations.CreateModel(
            name='DemandeLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(editable=False, max_length=20, unique=True, verbose_name='Numéro DL')),
                ('date_demande', models.DateField(default=datetime.date.today, verbose_name='Date de demande')),
                ('departement', models.CharField(max_length=10, verbose_name='Département demandeur')),
                ('chantier', models.CharField(max_length=255, verbose_name='Chantier/Projet')),
                ('duree_mois', models.IntegerField(help_text='Entre 1 et 6 mois', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(6)], verbose_name='Durée en mois')),
                ('budget_previsionnel_mru', models.DecimalField(decimal_places=3, default=Decimal('0.000'), editable=False, max_digits=15, verbose_name='Budget prévisionnel (MRU)')),
                ('statut', models.CharField(choices=[('BROUILLON', 'Brouillon'), ('SOUMISE', 'Soumise'), ('VALIDEE', 'Validée'), ('REJETEE', 'Rejetée'), ('MISE_A_DISPOSITION', 'Mise à disposition'), ('ENGAGEMENT_CREE', 'Engagement créé')], default='BROUILLON', max_length=20, verbose_name='Statut')),
                ('observations', models.TextField(blank=True, verbose_name='Observations')),
                ('date_validation', models.DateTimeField(blank=True, null=True, verbose_name='Date de validation')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('demandeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demandes_location', to=settings.AUTH_USER_MODEL, verbose_name='Demandeur')),
                ('validateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demandes_validees', to=settings.AUTH_USER_MODEL, verbose_name='Validateur')),
            ],
            options={
                'verbose_name': 'Demande de Location',
                'verbose_name_plural': 'Demandes de Location',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Engagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(editable=False, max_length=20, unique=True, verbose_name='Numéro CTL')),
                ('date_debut', models.DateField(verbose_name='Date de début')),
                ('date_fin', models.DateField(editable=False, verbose_name='Date de fin')),
                ('montant_total_estime_mru', models.DecimalField(decimal_places=3, default=Decimal('0.000'), editable=False, max_digits=15, verbose_name='Montant total estimé (MRU)')),
                ('conditions_particulieres', models.TextField(blank=True, verbose_name='Conditions particulières')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('responsable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='engagements_geres', to=settings.AUTH_USER_MODEL, verbose_name='Responsable engagement')),
            ],
            options={
                'verbose_name': 'Engagement (CTL)',
                'verbose_name_plural': 'Engagements (CTL)',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FichePointageMateriel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_fiche', models.CharField(max_length=50, verbose_name='Numéro de fiche')),
                ('periode_debut', models.DateField(verbose_name='Début de période')),
                ('periode_fin', models.DateField(verbose_name='Fin de période')),
                ('montant_total_calcule', models.DecimalField(decimal_places=3, default=Decimal('0.000'), editable=False, max_digits=15, verbose_name='Montant total calculé (MRU)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('engagement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fiches_pointage', to='core.engagement', verbose_name='Engagement')),
                ('materiel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fiches_pointage', to='core.materiellocation', verbose_name='Matériel pointé')),
            ],
            options={
                'verbose_name': 'Fiche de Pointage Matériel',
                'verbose_name_plural': 'Fiches de Pointage Matériel',
                'ordering': ['-periode_debut'],
                'unique_together': {('engagement', 'materiel', 'periode_debut')},
            },
        ),
        migrations.CreateModel(
            name='FicheVerificationPointage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chantier_verification', models.CharField(max_length=255, verbose_name='Chantier (vérification)')),
                ('mois_annee', models.CharField(max_length=20, verbose_name='Mois/Année')),
                ('date_verification', models.DateField(default=datetime.date.today, verbose_name='Date de vérification')),
                ('verificateur', models.CharField(max_length=100, verbose_name='Vérificateur')),
                ('total_consommation_carburant', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8, verbose_name='Total consommation carburant')),
                ('total_heures_facturees', models.IntegerField(default=0, verbose_name='Total heures à facturer')),
                ('conforme', models.BooleanField(default=True, verbose_name='Conforme')),
                ('observations_verification', models.TextField(blank=True, verbose_name='Observations de vérification')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('fiche_pointage', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fiche_verification', to='core.fichepointagemateriel', verbose_name='Fiche de pointage')),
            ],
            options={
                'verbose_name': 'Fiche de Vérification Pointage',
                'verbose_name_plural': 'Fiches de Vérification Pointage',
                'ordering': ['-date_verification'],
            },
        ),
        migrations.CreateModel(
            name='MaterielDemande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Quantité demandée')),
                ('sous_total', models.DecimalField(decimal_places=3, default=Decimal('0.000'), editable=False, max_digits=15, verbose_name='Montant Previsionnel TTC')),
                ('observations', models.TextField(blank=True, verbose_name='Observations spécifiques')),
                ('demande_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.demandelocation', verbose_name='Demande de location')),
                ('materiel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.materiellocation', verbose_name='Matériel')),
            ],
            options={
                'verbose_name': 'Matériel Demandé',
                'verbose_name_plural': 'Matériels Demandés',
                'unique_together': {('demande_location', 'materiel')},
            },
        ),
        migrations.AddField(
            model_name='demandelocation',
            name='materiels',
            field=models.ManyToManyField(related_name='demandes', through='core.MaterielDemande', to='core.materiellocation', verbose_name='Matériels demandés'),
        ),
        migrations.CreateModel(
            name='MiseADisposition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_mise_disposition', models.DateField(default=datetime.date.today, verbose_name='Date de mise à disposition')),
                ('immatriculation', models.CharField(max_length=50, verbose_name='Immatriculation/Référence')),
                ('conforme', models.BooleanField(default=True, verbose_name='Conforme aux spécifications')),
                ('observations', models.TextField(blank=True, verbose_name='Observations')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('demande_location', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mise_a_disposition', to='core.demandelocation', verbose_name='Demande de location')),
                ('fournisseur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mises_a_disposition', to='core.fournisseur', verbose_name='Fournisseur')),
                ('responsable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mises_a_disposition_gerees', to=settings.AUTH_USER_MODEL, verbose_name='Responsable acheteur')),
            ],
            options={
                'verbose_name': 'Mise à disposition',
                'verbose_name_plural': 'Mises à disposition',
                'ordering': ['-date_mise_disposition'],
            },
        ),
        migrations.AddField(
            model_name='engagement',
            name='mise_a_disposition',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='engagement', to='core.miseadisposition', verbose_name='Mise à disposition'),
        ),
        migrations.CreateModel(
            name='PointageJournalier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_pointage', models.DateField(verbose_name='Date')),
                ('jour_semaine', models.CharField(choices=[('LUNDI', 'Lundi'), ('MARDI', 'Mardi'), ('MERCREDI', 'Mercredi'), ('JEUDI', 'Jeudi'), ('VENDREDI', 'Vendredi'), ('SAMEDI', 'Samedi'), ('DIMANCHE', 'Dimanche')], max_length=10, verbose_name='Jour de la semaine')),
                ('compteur_debut', models.IntegerField(blank=True, null=True, verbose_name='Compteur début')),
                ('compteur_fin', models.IntegerField(blank=True, null=True, verbose_name='Compteur fin')),
                ('heures_panne', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=4, verbose_name='Heures panne')),
                ('heures_arret', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=4, verbose_name='Heures arrêt')),
                ('heures_travail', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=4, verbose_name='Heures travail')),
                ('consommation_carburant', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6, verbose_name='Consommation carburant (L)')),
                ('observations', models.TextField(blank=True, verbose_name='Observations')),
                ('montant_journalier', models.DecimalField(decimal_places=3, default=Decimal('0.000'), editable=False, max_digits=10, verbose_name='Montant journalier (MRU)')),
                ('fiche_pointage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pointages_journaliers', to='core.fichepointagemateriel', verbose_name='Fiche de pointage')),
            ],
            options={
                'verbose_name': 'Pointage Journalier',
                'verbose_name_plural': 'Pointages Journaliers',
                'ordering': ['date_pointage'],
                'unique_together': {('fiche_pointage', 'date_pointage')},
            },
        ),
    ]
