# Generated by Django 5.0.7 on 2025-09-10 12:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fichepointagemateriel',
            name='materiel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fiches_pointage', to='core.materieldemande', verbose_name='Matériel pointé'),
        ),
    ]
