# Generated by Django 5.0.7 on 2025-09-10 17:22

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_fichepointagemateriel_materiel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pointagejournalier',
            name='heures_arret',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=4, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('10.00'))], verbose_name='Heures arrêt'),
        ),
        migrations.AlterField(
            model_name='pointagejournalier',
            name='heures_panne',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=4, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('10.00'))], verbose_name='Heures panne'),
        ),
        migrations.AlterField(
            model_name='pointagejournalier',
            name='heures_travail',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=4, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('10.00'))], verbose_name='Heures travail'),
        ),
    ]
