# Generated by Django 5.0.7 on 2025-09-11 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_pointagejournalier_heures_arret_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='materiellocation',
            name='type_facturation',
            field=models.CharField(choices=[('PAR_JOUR', 'Prix Unitaire × Nombre Jours'), ('PAR_HEURE', 'Prix Unitaire × Total des Heures'), ('FORFAITAIRE', 'Prix Forfaitaire')], default='PAR_JOUR', max_length=15, verbose_name='Type de facturation'),
        ),
    ]
