# Generated by Django 5.0.7 on 2025-09-22 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_materiellocation_type_facturation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demandelocation',
            name='statut',
            field=models.CharField(choices=[('BROUILLON', 'Brouillon'), ('SOUMISE', 'Soumise'), ('VALIDEE', 'Validée'), ('REJETEE', 'Rejetée'), ('MISE_A_DISPOSITION', 'Mise à disposition'), ('ENGAGEMENT_CREE', 'Engagement créé')], default='SOUMISE', max_length=20, verbose_name='Statut'),
        ),
    ]
