# Generated by Django 5.0.8 on 2025-09-28 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_demandelocation_statut'),
    ]

    operations = [
        migrations.AddField(
            model_name='pointagejournalier',
            name='chantier_pointage',
            field=models.CharField(blank=True, help_text='Nom du chantier où le matériel a été utilisé ce jour. Laisser vide pour utiliser le chantier initial de la demande de location.', max_length=255, verbose_name='Chantier pointé'),
        ),
    ]
